FROM daskdev/dask-notebook:latest

RUN apt update && \
    apt-get install -y \
        build-essential \
        cmake \
        lsof \
        net-tools

RUN conda install -y -c conda-forge \
    dask-cloudprovider \
    dask-ml \
    scikit-learn \
    numpy \
    pandas \
    pytest && \
    pip install \
        awscli
